# Generated by Django 3.0.3 on 2020-02-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='gluten_free',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='lactose_free',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='vegan',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='vegetarian',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
