# Generated by Django 3.0.3 on 2020-02-18 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20200218_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restauranthours',
            options={'verbose_name': 'RestaurantHours', 'verbose_name_plural': 'RestaurantHours'},
        ),
    ]
