# Generated by Django 3.0.3 on 2020-02-19 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20200218_1955'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='restauranthours',
            unique_together={('weekday', 'restaurant')},
        ),
    ]
